version: "3.1"
services:
  webhost:
    image: "node:19.5.0"
    restart: unless-stopped
    user: "node"
    working_dir: /home/node/dt-stock-tracker
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/dt-stock-tracker
    expose:
      - "3000"
    command: "npm start"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpwd
  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpwd
      ME_CONFIG_MONGODB_URL: mongodb://root:testpwd@mongo:27017/
