version: "2"
services:
  node:
    image: "node:19.5.0"
    user: "node"
    working_dir: /home/node/dt-stock-tracker
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/dt-stock-tracker
    expose:
      - "3000"
    command: "npm start"
