version: "3.1"
services:
  webhost:
    build: .
    ports:
      - 3000:3000
    env_file: .env
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpwd
  express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpwd
      ME_CONFIG_MONGODB_URL: mongodb://root:testpwd@mongo:27017/
